version: '3'

services:

  elasticsearch:
    build: elasticsearch/
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  logstash:
    build: logstash/
    image: logstash
    ports:
      - "5000:5000"
      - "5050:5050"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    image: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch