FROM kibana:5.4.0
LABEL maintainer "andresgarcia.kaox@gmail.com"

#COPY config/kibana.yml /usr/share/kibana/config/kibana.yml

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
#RUN kibana-plugin install x-pack && kibana-plugin install license && kibana-plugin install shield

EXPOSE 5601:5601